title: OpenShift Play-ERQX
subTitle: Publish your blog-git-based easily at OpenShift
author: Rafa Paradela

disqus_shortname: 47degrees

theme: themes.Theme$

description: |
  <p>A <a href="http://www.47deg.com">47Degrees</a> test blog</p>
