title: OpenShift Play-ERQX
subTitle: Publish your blog-git-based easily at OpenShift
author: Rafa Paradela

disqus_shortname: 47degrees

theme: themes.Theme$

description: |
  <p>A 47Degrees experimental blog</p>
